### ISSUE TITLE
model_subfolder_name requires relative path

### ISSUE THREAD

**Issue by peterfoley** [rdrr1990/bigKRLS#10]
Dangers of using `setwd()` within a package notwithstanding, it's often useful to be able to put model/script outputs outside the script directory tree, but `model_subfolder_name` only accepts relative paths, which complicates that.

``` r
library(bigKRLS)
y <- as.matrix(mtcars$mpg)
X <- as.matrix(mtcars[,-1])
krls_out_temp <- tempfile()
out <- bigKRLS(y, X, model_subfolder_name = krls_out_temp)
#> starting bigKRLS... 
#> 
#> validating inputs, prepping data, etc...
#> Error in setwd(paste(c(wd.original, .Platform$file.sep, model_subfolder_name), : cannot change working directory
```

The `dir.create` call that precedes the error successfully creates a new empty subdirectory at the absolute path, though.

It appears that this is fixed by just changing the `setwd(paste(...,model_subfolder_name)` blocks to simply `setwd(model_subfolder_name)` since that will handle path expansion as needed, and will be consistent with the `dir.create` call.

**Comment by rbshaffer** [comment]
Makes sense to me. I recall having some strange path issues with an earlier version of the package, and if we're committed to using setwd() anyway it makes sense to just use that function all the way through.

**Comment by rdrr1990** [comment]
Thanks for looking into this, Peter! Since models can take some time to estimate, my major motivation was to make sure no big matrices were accidentally overwritten. Let's switch to `setwd()` normalization for now and then consider doing away with subfolders (presumably with a new, model-specific naming convention as opposed to e.g. `vcov.txt`).

**Comment by peterfoley** [comment]
I've got a PR for the `setwd` change (#11), and I'm also working on one to set up testing and code coverage via travis and codecov.

Once that testing is set up, I can take a crack at removing all uses of `setwd` and instead constructing the paths for save/load functions from the `model_subfolder_name` argument rather than current working directory.

**Comment by rdrr1990** [comment]
Thanks for such thorough code, @peterfoley! `bigKRLS` now no longer changes working directory when saving, loading, or operating on `big.matrix` objects in parallel (with the minor exception of the `.desc` files, which are handled in an improved manor as well).
