### ISSUE TITLE
need to complete Travis setup from rdrr1990/bigKRLS 

### ISSUE THREAD

**Issue by peterfoley** [rdrr1990/bigKRLS#14]
To enable testing from the rdrr1990/bigKRLS repo, you'll need to follow steps 1 and 2 here: https://docs.travis-ci.com/user/getting-started/#To-get-started-with-Travis-CI

After that, the tests should run on the next push.

You'll also need to update the badges in the README.md file to point to the correct locations for this repository's master branch, rather than my fork and branch:
```
[![Travis-CI Build Status](https://travis-ci.org/rdrr1990/bigKRLS.svg?branch=master)](https://travis-ci.org/rdrr1990/bigKRLS)
[![Coverage Status](https://img.shields.io/codecov/c/github/rdrr1990/bigKRLS/master.svg)](https://codecov.io/github/rdrr1990/bigKRLS?branch=master)
```

I'd recommend enabling Travis, then editing `README.md`, which will act as the push that will kick off tests on Travis and ensure everything is running properly.

**Comment by rdrr1990** [comment]
thanks again @peterfoley!
