### ISSUE TITLE
[Feature Request] add doc to the package

### ISSUE THREAD

**Issue by stevenlis** [rdrr1990/bigKRLS#32]
The `help()` returns nothing for the functions in the package.

![image](https://user-images.githubusercontent.com/33796896/61000566-b3625d00-a32b-11e9-8483-72f3a1fb1910.png)

Could you pls attached me a PDF of the doc since the package is not on CRAN now and I don't know where I could find it. 

https://www.rdocumentation.org/packages/bigKRLS/versions/3.0.5/topics/bigKRLS

**Comment by rdrr1990** [comment]
hi sorry that it is taking so long to get this back on CRAN. If you build the tar file found here: https://cran.r-project.org/src/contrib/Archive/bigKRLS/bigKRLS_3.0.5.tar.gz the vignette should load with the package as usual

**Comment by rdrr1990** [comment]
Back on CRAN, thanks for your patience!
